"""C18: one model card per model (reports/model_cards/), generated from the configs, the saved bundles and the
results matrix, so the numbers cannot drift from the models.

    python scripts/make_model_cards.py

Research models (LDA, DT, RF, XGB, MLP, AE, TabNet): per track, the training data, features, threshold rule and frozen
thresholds, within- vs cross-dataset results (mean ± std over seeds, run IDs in reports/tables/matrix_long.csv) and
known failure cases (automatic: the worst cross-dataset cells; curated: findings that numbers alone do not show).
Live-system models: the demo MLP, the nfs XGBoost (few-shot base), the adapter selector and the drift monitor.
"""

import json

import pandas as pd

from xnids.data import schema
from xnids.utils import config, paths

OUT = paths.REPORTS / "model_cards"
NAMES = {"lda": "Linear discriminant analysis", "dt": "Decision tree", "rf": "Random forest", "xgb": "XGBoost",
         "mlp": "Multilayer perceptron", "ae": "Autoencoder (benign-only anomaly detector)", "tabnet": "TabNet"}
TRACKS = {"cic77": "77 LycoSTand features (LycoS17 ↔ LycoS18: same extractor, different network)",
          "nf43": "39 NetFlow-v2 features (NF-UNSW-NB15 / NF-CSE-CIC-IDS2018 / NF-ToN-IoT)",
          "core": "15 features mapped across the CIC and NetFlow schemas (all five datasets)",
          "cic_orig": "78 original CICFlowMeter features (H2 only)"}
NOTES = {  # findings the matrix alone does not show (reports/FINDINGS.md)
    "all": ["Thresholds are frozen at 95% detection on SOURCE validation; target data never tunes them, so "
            "cross-dataset FPR / DR are what a deployment would see without recalibration.",
            "H1: across datasets the dominant failure is a detection and ranking collapse (134 of 136 cross cells), "
            "not always a rise in FPR (91 of 136).",
            "H3: ablating or normalising the C4 'lab-telling' features explains about 0% of the collapse; per-domain "
            "normalisation is worse than doing nothing."],
    "lda": ["Comparison with Cantone et al. (2024): LycoS18 → LycoS17 MCC 0.559 here vs 0.604 reported."],
    "xgb": ["Trained on GPU, predicts on CPU.",
            "C9: retrained with a few hundred labelled target flows (few-shot), it is the cheapest reliable recovery "
            "across datasets (MCC 0.92–0.94 with 1,000 labels); C11's best fixed action is XGBoost few-shot 200."],
    "mlp": ["Scores use a numerically stable sigmoid (expit) after an overflow on extreme NetFlow values (C8).",
            "C9: AdaBN / Tent help only within the LycoSTand family (cic77) and hurt across labs.",
            "C17: as a self-updating Tent loop it can be poisoned (see the demo MLP card)."],
    "ae": ["Trained on benign flows only; score = error / (error + q95 of benign validation error).",
           "H4: on LycoS17 its benign FPR stays ~1.3% over later days but jumps to 58.3% on the switch to LycoS18."],
    "tabnet": ["The first NF-UNSW runs did not learn with early-stopping patience 5; every TabNet run was redone with "
               "patience 10. compute_importance=False (feature-importance pass ran out of memory)."],
}


def fmt(m: float, s: float, pct: bool = False) -> str:
    if pd.isna(m):
        return "—"
    return f"{m * 100:.1f} ± {s * 100:.1f}%" if pct else f"{m:.3f} ± {0 if pd.isna(s) else s:.3f}"


def thresholds(model: str, track: str) -> pd.DataFrame:
    rows = []
    for d in sorted(paths.MODELS.glob(f"{model}-{track}-*")):
        t = paths.MODELS / d.name / "threshold.json"
        meta = paths.MODELS / d.name / "meta.json"
        if t.exists() and meta.exists():
            m = json.loads(meta.read_text())
            td = m.get("training_data", {})
            rows.append({"source": td.get("dataset"), "seed": m.get("seed"), "variant": td.get("split_variant"),
                         "threshold": json.loads(t.read_text())["threshold"], "n_train": td.get("n_train"),
                         "split_hash": td.get("split_hash"), "bundle": d.name})
    return pd.DataFrame(rows)


def research_card(model: str) -> str:
    mcfg = config.load(paths.CONFIGS / "train/models" / f"{model}.yaml")["model"]
    lines = [f"# Model card: {NAMES[model]} (`{model}`)", "",
             "Research model of the cross-dataset study (C5/C6). Generated by `scripts/make_model_cards.py`.", "",
             "## Model", "", f"- Parameters: `{json.dumps(mcfg.get('params', {}))}`"]
    if mcfg.get("grid"):
        lines.append(f"- Grid (chosen by the lowest FPR at 95% DR on source validation): `{json.dumps(mcfg['grid'])}`")
    lines += ["- Preprocessing: median imputation and constant-column removal fitted on source train only "
              "(`preprocess.json` in each bundle).", "- Seeds: 0, 1, 2 (mean ± std below).", ""]
    for track in TRACKS:
        f = paths.TABLES / f"matrix_{track}.csv"
        if not f.exists():
            continue
        mt = pd.read_csv(f)
        mt = mt[mt.model == model]
        if mt.empty:
            continue
        th = thresholds(model, track)
        feats = schema.features(track)
        lines += [f"## Track `{track}`: {TRACKS[track]}", "",
                  f"- Features: {len(feats)} (`configs/tracks/{track}.yaml`); identifiers excluded by the schema "
                  "check; `dst_port` kept but flagged where present.", ""]
        if len(th):
            g = th[th.variant.isna()].groupby("source").agg(thr=("threshold", "mean"), thr_sd=("threshold", "std"),
                                                             n_train=("n_train", "first"),
                                                             split=("split_hash", "first"))
            lines += ["| Source (training data) | Train rows | Split hash | Frozen threshold (mean ± std) |",
                      "|---|---|---|---|"]
            for src, r in g.iterrows():
                sd = 0.0 if pd.isna(r.thr_sd) else r.thr_sd
                lines.append(f"| {src} | {int(r.n_train):,} | `{r.split}` | {r.thr:.6g} ± {sd:.2g} |")
            lines.append("")
        lines += ["| Source → target | Kind | FPR at thr | DR at thr | MCC | PR-AUC |", "|---|---|---|---|---|---|"]
        for _, r in mt.sort_values(["source", "kind", "target"], ascending=[True, False, True]).iterrows():
            lines.append(f"| {r.source} → {r.target} | {r.kind} | {fmt(r.fpr_at_thr_mean, r.fpr_at_thr_std, True)} "
                         f"| {fmt(r.dr_at_thr_mean, r.dr_at_thr_std, True)} | {fmt(r.mcc_at_thr_mean, r.mcc_at_thr_std)} "
                         f"| {fmt(r.pr_auc_mean, r.pr_auc_std)} |")
        if (mt[["fpr_at_thr_std", "dr_at_thr_std", "mcc_at_thr_std"]].fillna(0) == 0).all().all():
            lines += ["", "The three seeds give identical results on this track: training is deterministic for this "
                          "model (no row / column subsampling), so the seed changes nothing."]
        cross = mt[mt.kind == "cross"].sort_values("mcc_at_thr_mean")
        if len(cross):
            w = cross.head(3)
            lines += ["", "Worst cross-dataset cells: " + "; ".join(
                f"{r.source} → {r.target} (MCC {r.mcc_at_thr_mean:.2f}, DR {r.dr_at_thr_mean:.0%}, "
                f"FPR {r.fpr_at_thr_mean:.0%})" for _, r in w.iterrows()) + "."]
        lines.append("")
    lines += ["## Known failure cases and notes", ""] + [f"- {n}" for n in NOTES["all"] + NOTES.get(model, [])]
    lines += ["", "## Intended use", "",
              "Research measurement of cross-dataset generalisation on public lab datasets. Not a production detector: "
              "every result above shows it must be revalidated (and usually adapted with labels) on the network it "
              "is deployed in.", "", "## Provenance", "",
              "Bundles: `models/<model>-<track>-<source>-s<seed>-<cfg_hash>/` (meta.json holds the MLflow run ID, "
              "git commit and split hash). Every matrix cell lists its run IDs in `reports/tables/matrix_<track>.csv`."]
    return "\n".join(lines) + "\n"


def live_cards() -> dict[str, str]:
    seg = pd.read_csv(paths.TABLES / "c13_demo_segments.csv")
    a, b1 = seg[seg.segment == "A"].iloc[0], seg[seg.segment == "B1"].iloc[0]
    acts = pd.read_csv(paths.TABLES / "c14_actions_in_B.csv")
    cal = json.loads((paths.MODELS / "monitor/nfs-nfs17.json").read_text())
    sel = json.loads((paths.MODELS / "selector/meta.json").read_text())
    mlp = pd.read_csv(paths.TABLES / "matrix_long.csv")
    mlp = mlp[(mlp.track == "nfs")] if "nfs" in set(mlp.track) else None
    demo = [
        "# Model card: demo detector (MLP on NFStream flows, `mlp-nfs-nfs17-s0-…`)", "",
        "Active model of the live system (C13–C16). Generated by `scripts/make_model_cards.py`.", "",
        "## Data", "",
        "- Training: CIC-IDS2017 Monday, Wednesday and Friday PCAPs → NFStream (frozen `configs/nfstream.yaml`, TCP "
        "termination plugin) → LycoS17 labelling rules (`nfs17`). Time-block split; Wednesday 13:30–13:55 UTC held "
        "out entirely (it is replay segment A).",
        f"- Features: {len(schema.features('nfs'))} NFStream statistical features (`configs/tracks/nfs.yaml`).",
        "- Threshold: 95% DR on source validation, frozen.", "",
        "## Performance", "",
        "- Within nfs17 (3 seeds): FPR 1.2–2.3% at DR 94–95%, MCC 0.90–0.94.",
        "- On CSE-CIC-IDS2018 (nfs18 test): FPR 4.7–5.5%, DR 0.1–1.1%.",
        f"- Demo replay, seed 0: benign FPR {a.fpr:.2%} on segment A (held-out 2017) vs {b1.fpr:.2%} on segment B1 "
        "(2018); DoS-Hulk DR 94% → 1.2%.", "",
        "## Known failure cases", "",
        "- A different network breaks it: false positives rise about 10×, mostly on 2-packet flows to SMB / telnet / "
        "HTTPS / SSH, and the 2018 DoS-Hulk is missed.",
        "- It flags the 2018 'DoS-SlowHTTPTest' (refused connections to port 21) because they look like port scans, "
        "not because it recognises slow HTTP.",
        "- Label-free adaptation does not fix the new network: AdaBN / scaling / CORAL raise canary FPR to 13–41% and "
        "are blocked by the gates; only XGBoost few-shot with labelled flows from the new network passes them "
        "(segment-B1 FPR 10.75% → 0.5–1.5%).",
        "- C17: as a self-updating Tent loop, an attacker who can query its score and controls 5–10% of the "
        "adaptation traffic drives DDoS detection from 100% to 1.6% within 30 rounds, without raising FPR. Guards "
        "anchored to the original model (canary, rollback) stop this; per-step checks do not.", "",
        "## Intended use", "", "Live demonstration of drift detection and human-approved adaptation on replayed lab traffic."]
    xgb = [
        "# Model card: XGBoost on NFStream flows (`xgb-nfs-nfs17-s0-…`)", "",
        "Base model of the `xgb:fewshot(...)` adaptation action (C14). Same data, features and threshold rule as the "
        "demo MLP.", "",
        "- Within nfs17: FPR 0.86% at DR 92%, MCC 0.93. On nfs18: DR 0%.",
        "- Few-shot (source train + labelled target flows upweighted to 20%): the only action that passes every gate "
        "in segment B. Results on segment B (`c14_actions_in_B.csv`): " + "; ".join(
            f"{r.action}: B1 FPR {r.fpr_B1:.2%}" for _, r in acts[acts.action.str.startswith("xgb")].iterrows()) + ".",
        "- Failure case: with 200 labels and target weight 0.2, about 1 pool in 41 yields a candidate that fails the "
        "canary-FPR gate (C16); the dashboard's Reject & rebuild draws a new label sample.",
        "- With fewer than 5 attacks in the labelled budget the threshold is re-picked on source validation (fixed "
        "in C14: keeping the frozen threshold made a retrained model alert on every flow)."]
    selector = [
        "# Model card: adapter selector (`models/selector/`)", "",
        "Bootstrap ensemble of 5 LightGBM regressors predicting each action's MCC gain minus label cost from the "
        "label-free drift features of a window (C11).", "",
        f"- Training data: the C10 adaptation log ({sel.get('cfg_hash', '')}), 6,500 rows over 8 dataset pairs; "
        f"utility = {sel['utility']}, label cost {sel['label_cost']} per label.",
        f"- Drift features: {', '.join(sel['drift_cols'])}.",
        "- Leave-one-pair-out regret 0.077 vs 0.050 for the best fixed action (XGBoost few-shot 200): it does not beat "
        "the best fixed action on average (beats it on 3 of 8 held-out pairs).",
        "- In the live system it chooses among the enabled actions (`configs/live.yaml`) and recommends XGBoost "
        "few-shot 200 on the new network, the action that works there.",
        f"- MLflow run: `{sel['run_id']}`."]
    monitor = [
        "# Model card: live drift monitor (`models/monitor/nfs-nfs17.json`)", "",
        "Calibrated for time-ordered real traffic (C15).", "",
        f"- Statistic: share of a window's flows whose nearest reference flow (standardised MLP embedding) is farther "
        f"than {cal['quantile']:.0%} of held-out source flows (flow cutoff {cal['novelty_tau']:.3f}).",
        f"- Window threshold: {cal['thresholds']['novelty_share']:.3%} novel flows, the 99th percentile over "
        f"{cal['null_windows']} time-ordered windows of raw (not deduplicated) 2017 traffic; alert after 2 "
        "consecutive windows over it.",
        "- Demo replay: 0 of 35 segment-A windows alert; first alert at the 2nd window of the new network.",
        "- Known failure: the C8 monitor (KS / MMD / ADWIN + cost trigger) false-alarmed on 34 of 35 in-distribution "
        "windows of real traffic; KS / MMD cannot tell an attack burst from a new network. ATC's estimated error "
        "rise was higher on in-distribution traffic than on the new network, so it is not used for alerting.",
        "- Novelty in input space missed the evasive DoS-Hulk windows (20% over threshold vs 80% in embedding space)."]
    return {"demo_mlp_nfs.md": "\n".join(demo) + "\n", "xgb_nfs.md": "\n".join(xgb) + "\n",
            "selector.md": "\n".join(selector) + "\n", "drift_monitor.md": "\n".join(monitor) + "\n"}


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    written = []
    for m in NAMES:
        (OUT / f"{m}.md").write_text(research_card(m))
        written.append(f"{m}.md")
    for name, text in live_cards().items():
        (OUT / name).write_text(text)
        written.append(name)
    index = ["# Model cards", ""] + [f"- [{w}]({w})" for w in written]
    (OUT / "README.md").write_text("\n".join(index) + "\n")
    print("wrote", ", ".join(written))


if __name__ == "__main__":
    main()
